### ISSUE TITLE
Extension Activating on Non-Wolfram Code (Python)

### ISSUE THREAD

**Issue by singularitti** [markjet7/wlsp#3]
Hello,

First of all, thank you for developing this extension. It's been quite useful for my work with Wolfram language in VSCode.

However, I've encountered an issue where the extension activates on my Python files, causing parts of my code to be unnecessarily rendered in red (semantic token key: `function`). This is affecting the readability and usability of the editor for my Python projects.

Upon checking the `package.json` file, I noticed that `"activationEvents": []` is left empty. I attempted to fill in `"wolfram"`, but I'm unsure if this is the correct approach to ensure the extension only activates on Wolfram files.

I know this extension does not seem to be activated, but when I disable it, everything looks normal again.

Could you please reproduce and address this issue? Here is a screenshot of the problem for reference:

<img width="782" alt="image" src="https://github.com/markjet7/wlsp/assets/25192197/aebec202-f0d6-496d-839b-a38a50c4b0df">

```
Extension Version: 0.0.73
VSCode Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:34:48.028Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

**Comment by markjet7** [comment]
Hello,

Thank you for testing this code and raising this issue.
You are correct that the language activates automatically because of the empty activationEvents.
I will issue a temporary fix soon which is to change it to:
"activationEvents": ["onLanguage:wolfram"]

See explanation [here](https://code.visualstudio.com/api/references/activation-events#:~:text=json%20extension%20manifest.-,onLanguage,a%20certain%20language%20gets%20opened.&text=The%20onLanguage%20event%20takes%20a,entries%20in%20the%20activationEvents%20array.).

**Comment by singularitti** [comment]
Thank you for your timely reply!

**Comment by singularitti** [comment]
Hi, I have tried the latest version. But the same bug still exists?

**Comment by markjet7** [comment]
Hello - Sorry for the semantic highlighting issue. 
We did find that the extension enabled semantic highlighting for all languages, and have fixed it.
Just in case, you can also check your json settings and set 
            "editor.semanticHighlighting.enabled": false
This can also be set true or false on an individual language basis. 
Thank you

**Comment by markjet7** [comment]
Hi Qi, a new version has been posted to address an issue related to the theme colors.
Are you having the same issue?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by singularitti** [comment]
Hi @markjet7, setting `editor.semanticHighlighting.enabled` to `false` did solve this problem. However, this is different from the default value of VSCode and might affect other extensions I have installed. Would there be a better way of resolving it? Thank you!

**Comment by markjet7** [comment]
Hi Qi - yes, the latest version 0.0.77 has this fixed already. You can install from the marketplace or GitHub.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by singularitti** [comment]
Hi @markjet7, I was trying 0.0.77. But setting `editor.semanticHighlighting.enabled` to `false` seems too strong a constraint. Would you mind providing a more flexible solution? Thank you!
